[package]
name = "password_generator"
version = "0.1.0"
edition = "2024"
description = "a simple password generator"
license = "MIT"

[dependencies]
clap = { version = "4.5.45", features = ["default", "cargo"] }
rand = "0.9.2"
